### ISSUE TITLE
DP NTriples data dump provided contains invalid  geo typed wkt literals

### ISSUE THREAD

**Issue by imitko** [MillenniumDB/WDBench#2]

**Comment by imitko** [comment]
<http://www.wikidata.org/entity/Q5187625> <http://www.wikidata.org/prop/direct/P625> "<http://www.wikidata.org/entity/Q111> Point(349.8 5.1)"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .
<http://www.wikidata.org/entity/Q5187625> <http://www.wikidata.org/prop/direct/P625> "<http://www.wikidata.org/entity/Q111> Point(349.86 5.08)"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .

**Comment by cbuil** [comment]
Dear Imitko

I do not totally understand: the dump comes directly from Wikidata. It is not whether it is good or bad, it is what it is because it is what Wikidata has.

Best

**Comment by imitko** [comment]
@cbuil 
ok, so this is a problem in wikidata dump itself.
