### ISSUE TITLE
Slow import times for Blazegraph

### ISSUE THREAD

**Issue by SergiuBordei** [MillenniumDB/WDBench#3]
Dear Professors,

I am attempting to replicate the WDBench study for my bachelor's degree.

The VM I am using has the following specs:
- AMD EPYC 7352 24-Core Processor, 2300 MHz
- Samsung PM1733 NVMe (17TB)
- AMD Starship/Matisse mixes (128GB total)

I encountered extremely slow import times for the current truthy data into Blazegraph.

What were the waiting times for the truthy data import in the study?

Mine will take over 5 days.

The study mentions that the import time is over one week for the entire Wikidata data.

Should over 5 days of import be a common/normal occurrence?

Thank you for your contribution to the field of graph databases.

**Comment by cirojas** [comment]
Your processor and disk are better than the ones we used, so it shouldn't take more than 4 days.

Maybe is a problem with a repository version.
After the commands in the README:
- `git clone --recurse-submodules https://gerrit.wikimedia.org/r/wikidata/query/rdf wikidata-query-rdf`
- `cd wikidata-query-rdf`

Add this command to use the same commit that we used:
- `git checkout query-service-parent-0.3.82`
